from datetime import timedelta

import pytest
from flask_session.redis import RedisSessionInterface

from config import ProductionConfig, _environment_int


def test_application_factory_registers_complete_application_wiring(app):
    assert isinstance(app.session_interface, RedisSessionInterface)
    assert "money" in app.jinja_env.filters
    assert "cart_total" in app.jinja_env.filters
    assert {
        "store.index",
        "cart.checkout",
        "admin.dashboard",
        "health.readiness",
    } <= {rule.endpoint for rule in app.url_map.iter_rules()}


def test_application_factory_rejects_missing_required_settings(app_factory):
    with pytest.raises(
        RuntimeError,
        match="Missing required configuration: SECRET_KEY",
    ):
        app_factory(SECRET_KEY=None)


def test_application_factory_rejects_invalid_session_lifetime(app_factory):
    with pytest.raises(
        RuntimeError,
        match="PERMANENT_SESSION_LIFETIME must be a positive duration",
    ):
        app_factory(PERMANENT_SESSION_LIFETIME=timedelta())


@pytest.mark.parametrize("setting", ["PRODUCTS_PER_PAGE", "ADMIN_PER_PAGE"])
def test_application_factory_rejects_invalid_page_sizes(app_factory, setting):
    with pytest.raises(RuntimeError, match=f"{setting} must be a positive integer"):
        app_factory(**{setting: 0})


def test_application_factory_requires_a_generated_admin_password_hash(app_factory):
    with pytest.raises(RuntimeError, match="must be generated by Werkzeug"):
        app_factory(ADMIN_PASSWORD_HASH="plaintext-password")


def test_environment_integer_reports_the_invalid_setting(monkeypatch):
    monkeypatch.setenv("NEXUS_TEST_INTEGER", "invalid")

    with pytest.raises(RuntimeError, match="NEXUS_TEST_INTEGER must be an integer"):
        _environment_int("NEXUS_TEST_INTEGER", 1)


def test_production_profile_enforces_secure_session_cookies():
    assert ProductionConfig.SESSION_COOKIE_SECURE is True
    assert ProductionConfig.ALLOW_DB_CLEAN is False
    assert ProductionConfig.WTF_CSRF_ENABLED is True
